# Dockerfile
FROM python:3.9.10-alpine3.14
WORKDIR /src
RUN pip install --upgrade pip
COPY ./requirements.txt /src/requirements.txt
RUN pip install -r requirements.txt
# RUN pip install flask
# RUN pip install openai
ENV FLASK_APP=app
CMD ["python","server.py"]